# Generated by Django 2.2 on 2022-03-01 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categ',
            options={'ordering': ('name',), 'verbose_name': 'cateory', 'verbose_name_plural': 'categories'},
        ),
    ]
